//10
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("2.0.6.0")]
[assembly: AssemblyVersion("2.0.6.0")]

namespace SimpleLogistics
{
    public static class Version
    {
        public const int major = 2;
        public const int minor = 0;
        public const int patch = 6;
        public const int build = 0;
        public const string Number = "2.0.6.0";
#if DEBUG
		public const string Text = Number + " DEBUG";
#else
        public const string Text = Number + "";
#endif
    }
}